application:
  version: v1.0.0
  name: base
  desc: API documentation for API Base Spring Boot
  contact:
    name: Sendi Agustian
    email: admin@sendistudio.id

spring:
    # Debugging configuration
    devtools:
        add-properties: false
        restart:
            enabled: true
            additional-paths: src
    # Banner configuration
    banner:
        location: "classpath:assets/banner.txt"

    # External configuration files
    config:
        import:
        - "classpath:properties/server.yaml"
        - "classpath:properties/logging.yaml"
        - "classpath:properties/database.yaml"
        - "classpath:properties/resilience4j.yaml"
        - "classpath:properties/third-party.yaml"
        - "classpath:properties/scalar.yaml"

    # Web configuration
    web:
        resources:
            add-mappings: true
        error:
            include-message: always
            include-binding-errors: never
            include-stacktrace: never